# Generated by Django 6.0.6 on 2026-09-02 09:04

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactivetemplate",
            name="implementation",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("ZIP", "ZIP (Zip the data)"),
                    ("COMBINELATEST", "COMBINELATEST (Combine values with latest value from each stream)"),
                    ("WITHLATEST", "WITHLATEST (Combine a leading value with the latest value)"),
                    ("BUFFER_COMPLETE", "BUFFER_COMPLETE (Buffer values until complete is retrieved)"),
                    ("BUFFER_UNTIL", "BUFFER_UNTIL (Buffer values until signal is send)"),
                    ("BUFFER_COUNT", "BUFFER_COUNT (Butffer values until the count is reacht)"),
                    ("DELAY", "DELAY (Delay the data)"),
                    ("DELAY_UNTIL", "DELAY_UNTIL (Delay the data until signal is send)"),
                    ("CHUNK", "CHUNK (Chunk the data)"),
                    ("SPLIT", "SPLIT (Split the data)"),
                    ("OMIT", "OMIT (Omit the data)"),
                    ("ENSURE", "ENSURE (Ensure the data (discards None in the stream))"),
                    ("SELECT", "SELECT (Select a key from the data)"),
                    ("ADD", "ADD (Add a number to the data)"),
                    ("SUBTRACT", "SUBTRACT (Subtract a number from the data)"),
                    ("MULTIPLY", "MULTIPLY (Multiply the data with a number)"),
                    ("DIVIDE", "DIVIDE (Divide the data with a number)"),
                    ("MODULO", "MODULO (Modulo the data with a number)"),
                    ("POWER", "POWER (Power the data with a number)"),
                    ("JUST", "JUST (Emit a constant value)"),
                    ("PREFIX", "PREFIX (Prefix the data with a string)"),
                    ("SUFFIX", "SUFFIX (Suffix the data with a string)"),
                    ("FILTER", "FILTER (Filter the data of a union)"),
                    ("REORDER", "REORDER (Reorder the data)"),
                    ("GATE", "GATE (Gate the data, first value is gated, second is gate)"),
                    ("TO_LIST", "TO_LIST (Convert to list)"),
                    ("FOREACH", "FOREACH (Foreach element in list)"),
                    ("IF", "IF (If condition is met)"),
                    ("AND", "AND (AND condition)"),
                    ("ALL", "ALL (establish if all values are Trueish)"),
                ],
                default="ZIP",
                help_text="Check async Programming Textbook",
                max_length=1000,
            ),
        ),
    ]
