# Generated by Django 4.2.9 on 2024-07-04 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0003_runevent_reference"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RunSnapshot",
            new_name="Snapshot",
        ),
    ]
