# Generated by Django 4.2.9 on 2024-07-04 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0004_rename_runsnapshot_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
