# Generated by Django 4.2.9 on 2024-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0005_run_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="runevent",
            name="exception",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(default="RUNNING", max_length=100),
        ),
    ]
