# Generated by Django 4.2.9 on 2024-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0006_runevent_exception_alter_run_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runevent",
            name="exception",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
